name: Kernel Compilation

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        type: string
      include_next:
        description: 'Include NEXT?'
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up build environment
        run: |
          sudo apt update -y
          sudo apt install libncurses5-dev -y
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
          sudo dpkg -i libtinfo5_6.3-2ubuntu0.1_amd64.deb

      - name: Set environment variable
        run: |
          echo "BUILD_KERNEL_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          echo "INCLUDE_NEXT=${{ github.event.inputs.include_next }}" >> $GITHUB_ENV

      - name: Compile Kernel
        run: |
          bash build_kernel.sh ${{ github.event.inputs.include_next }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: KernelSU-Next-SM-S711B-${{ github.event.inputs.tag }}
          path: build/*.tar

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          name: "KernelSU-Next-SM-S711B-${{ github.event.inputs.tag }}"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "build/*.tar"
          body: "Commit SHA: ${{ github.sha }}"
